#!/bin/bash
# Combines spike files generated by different MPI ranks.

combine ()
{

    echo "Combining spike files"

    for stage in "A" "B" "C" "D" "E";
    do
        LC_ALL=C sort -k "2" -m -n --parallel=16 "spikes-E-$stage-"*".gdf" > "spikes-E-$stage.gdf"
        LC_ALL=C sort -k "2" -m -n --parallel=16 "spikes-I-$stage-"*".gdf" > "spikes-I-$stage.gdf"
    done

    # remove per rank files
    rm -f spikes-E-?-*.gdf
    rm -f spikes-I-?-*.gdf
    exit 0
}

combine
